### ISSUE TITLE
Criar um tutorial ou tour guiado para os novatos

### ISSUE THREAD

**Issue by carloscesar182** [rhuangabrielsantos/dots-game#11]
@rhuangabrielsantos apesar de ser bem simples e intuitivo pra quem já conhece, na primeira vez que fui jogar tive que sair clicando aleatoriamente pra entender como funcionava.
Talvez seria legal ter um tutorial simples ou um tour guiado com umas 4 ou 5 jogadas só pra ver a dinâmica do jogo

Parabéns pelo projeto!!

**Comment by rhuangabrielsantos** [comment]
Opa @carloscesar182, agradeço a issue!!
Atualmente já existe um tutorial bem simples, indicado pelo ícone de interrogação no canto inferior direito, acredito que uma boa melhoria é deixar mais claro para o que ele serve!

![image](https://user-images.githubusercontent.com/50742592/161870510-7c82db32-02e3-4f38-b431-884c8b436e09.png)

![image](https://user-images.githubusercontent.com/50742592/161870526-02a128f8-eabd-44a7-83e3-4e9d55d041b8.png)

Talvez um texto que fique visível por alguns segundos indicando que ali existe um tutorial, o que acha da ideia?

**Comment by carloscesar182** [comment]
eu vi só depois que abri a issue, sry
achei que era algo como um "sobre" do site e nem cliquei logo de cara.
vlw Danilinho

**Comment by rhuangabrielsantos** [comment]
Sem problemas!! Mas vou pensar em algo para melhorar a UX nesse ponto, tmjj!
