### ISSUE TITLE
Quando ninguém seleciona cor alguma, as linhas ficam invisíveis

### ISSUE THREAD

**Issue by manbomb** [rhuangabrielsantos/dots-game#5]
Daria pra colocar uma cor por padrão para cada player, eu testei no offline, sem selecionar nenhuma cor pra ninguém e as linhas ficaram invisíveis e o jogo continuou normalmente.

**Comment by rhuangabrielsantos** [comment]
Opa @manbomb!
Muito obrigado pelo feedback, no modo online existe uma validação para quando o usuário não seleciona a cor, irei adicionar aí também!

**Comment by rhuangabrielsantos** [comment]
@manbomb subi a correção, se quiser testar novamente!

ps: Limpe o cache antes de testar hehe

**Comment by manbomb** [comment]
Ficou top kkkkk @rhuangabrielsantos
